source ~/.zsh/antigen.zsh


# frameworks
antigen use oh-my-zsh
#antigen use prezto

# oh-my-zsh plugins
antigen bundles <<EOBUNDLES
    robbyrussell/oh-my-zsh plugins/colored-man-pages
    robbyrussell/oh-my-zsh plugins/colorize
    robbyrussell/oh-my-zsh plugins/cp
    robbyrussell/oh-my-zsh plugins/per-directory-history
    robbyrussell/oh-my-zsh plugins/pip
    robbyrussell/oh-my-zsh plugins/python
    robbyrussell/oh-my-zsh plugins/safe-paste
    robbyrussell/oh-my-zsh plugins/sudo
    robbyrussell/oh-my-zsh plugins/virtualenv
    robbyrussell/oh-my-zsh plugins/web-search
EOBUNDLES

# other plugins
antigen bundles <<EOBUNDLES
    arialdomartini/oh-my-git

    MichaelAquilina/zsh-autoswitch-virtualenv

    zsh-users/zsh-syntax-highlighting
    zsh-users/zsh-autosuggestions
    zsh-users/zsh-completions
    zsh-users/zsh-history-substring-search
EOBUNDLES

# theme
#antigen theme agnoster/agnoster-zsh-theme agnoster
antigen theme bhilburn/powerlevel9k powerlevel9k

P9KGT_BACKGROUND='dark'
P9KGT_COLORS='light'
#P9KGT_FONTS='awesome-patched'
if [[ $P9KGT_BACKGROUND == 'light' ]]
then
	POWERLEVEL9K_COLOR_SCHEME='light'
	P9KGT_TERMINAL_BACKGROUND=231
elif [[ $P9KGT_BACKGROUND == 'dark' ]]
then
	POWERLEVEL9K_COLOR_SCHEME='dark'
	P9KGT_TERMINAL_BACKGROUND=236
fi
if [[ $P9KGT_COLORS == 'light' ]]
then
	P9KGT_RED=009
	P9KGT_GREEN=010
	P9KGT_YELLOW=011
	P9KGT_BLUE=012
elif [[ $P9KGT_COLORS == 'dark' ]]
then
	P9KGT_RED=001
	P9KGT_GREEN=002
	P9KGT_YELLOW=003
	P9KGT_BLUE=004
elif [[ $P9KGT_COLORS == 'bright' ]]
then
	P9KGT_RED=196
	#P9KGT_GREEN=148
	P9KGT_GREEN=154
	P9KGT_YELLOW=220
	P9KGT_BLUE=075
fi

export export AUTOSWITCH_VIRTUAL_ENV_DIR=".venv"

DEFAULT_USER='ntauthority'

POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND=$P9KGT_YELLOW
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=$P9KGT_YELLOW
POWERLEVEL9K_CONTEXT_SUDO_FOREGROUND=$P9KGT_YELLOW
POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND=$P9KGT_YELLOW
POWERLEVEL9K_CONTEXT_REMOTE_SUDO_FOREGROUND=$P9KGT_YELLOW
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND=$P9KGT_TERMINAL_BACKGROUND
POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND=$P9KGT_TERMINAL_BACKGROUND
POWERLEVEL9K_CONTEXT_SUDO_BACKGROUND=$P9KGT_TERMINAL_BACKGROUND
POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND=$P9KGT_TERMINAL_BACKGROUND
POWERLEVEL9K_CONTEXT_REMOTE_SUDO_BACKGROUND=$P9KGT_TERMINAL_BACKGROUND
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND=$P9KGT_YELLOW
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND=$P9KGT_RED
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND=$P9KGT_TERMINAL_BACKGROUND
POWERLEVEL9K_DIR_HOME_FOREGROUND=$P9KGT_TERMINAL_BACKGROUND
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND=$P9KGT_TERMINAL_BACKGROUND
POWERLEVEL9K_DIR_ETC_FOREGROUND=$P9KGT_TERMINAL_BACKGROUND
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND=$P9KGT_BLUE
POWERLEVEL9K_DIR_HOME_BACKGROUND=$P9KGT_BLUE
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND=$P9KGT_BLUE
POWERLEVEL9K_DIR_ETC_BACKGROUND=$P9KGT_BLUE
POWERLEVEL9K_VCS_CLEAN_FOREGROUND=$P9KGT_TERMINAL_BACKGROUND
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=$P9KGT_TERMINAL_BACKGROUND
POWERLEVEL9K_VCS_CLOBBERED_FOREGROUND=$P9KGT_TERMINAL_BACKGROUND
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=$P9KGT_TERMINAL_BACKGROUND
POWERLEVEL9K_VCS_CLEAN_BACKGROUND=$P9KGT_GREEN
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=$P9KGT_YELLOW
POWERLEVEL9K_VCS_CLOBBERED_BACKGROUND=$P9KGT_RED
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=$P9KGT_GREEN
POWERLEVEL9K_STATUS_CROSS=true
POWERLEVEL9K_STATUS_OK_FOREGROUND=$P9KGT_GREEN
POWERLEVEL9K_STATUS_ERROR_FOREGROUND=$P9KGT_RED
POWERLEVEL9K_STATUS_OK_BACKGROUND=$P9KGT_TERMINAL_BACKGROUND
POWERLEVEL9K_STATUS_ERROR_BACKGROUND=$P9KGT_TERMINAL_BACKGROUND
POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND=$P9KGT_YELLOW
POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND=$P9KGT_TERMINAL_BACKGROUND
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=$P9KGT_TERMINAL_BACKGROUND
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=$P9KGT_YELLOW

#POWERLEVEL9K_MODE=nerdfont-complete
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
#POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
#POWERLEVEL9K=truncate_beginning
#POWERLEVEL9K_TIME_BACKGROUND=black
#POWERLEVEL9K_TIME_FOREGROUND=white
#POWERLEVEL9K_TIME_FORMAT=%D{%I:%M}
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%F{blue}╭─%F{red}'
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%F{blue}╰⨠%f '
#POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=$'\uE0B1'
#POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=$'\uE0B3'
POWERLEVEL9K_STATUS_VERBOSE=true
POWERLEVEL9K_VCS_CLEAN_FOREGROUND=black
POWERLEVEL9K_VCS_CLEAN_BACKGROUND=green
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=black
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=yellow
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=white
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=black
POWERLEVEL9K_VCS_UNTRACKED_ICON=●
POWERLEVEL9K_VCS_UNSTAGED_ICON=±
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON=↓
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON=↑
#POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=black
#POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=blue
POWERLEVEL9K_FOLDER_ICON='📁'
POWERLEVEL9K_CUSTOM_OS_ICON='echo 🎩 '
POWERLEVEL9K_CUSTOM_OS_ICON_BACKGROUND=red
POWERLEVEL9K_CUSTOM_OS_ICON_FOREGROUND=white
POWERLEVEL9K_PYTHON_ICON=🐍
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(custom_os_icon ssh root_indicator dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(command_execution_time status vi_mode virtualenv time)

# conda
__conda_setup="$('/usr/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/usr/etc/profile.d/conda.sh" ]; then
        . "/usr/etc/profile.d/conda.sh"
    else
        export PATH="/usr/bin:$PATH"
    fi
fi
unset __conda_setup

# local overrides
if [ -f ~/.zshrc_local ]; then
    source ~/.zshrc_local
fi

antigen apply

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

